### ISSUE TITLE
new rocsolver build error with fmt 9

### ISSUE THREAD

**Issue by nidjan** [ROCmSoftwarePlatform/rocSOLVER#476] opened 2022-10-01 18:49 UTC
Manjaro, aur build rocsolver
`[ 10%] Building CXX object library/src/CMakeFiles/rocsolver.dir/specialized/roclapack_getri_specialized_kernels_c.cpp.o

In file included from /var/tmp/pamac-build-chameleon/rocsolver/src/rocSOLVER-rocm-5.2.3/library/src/common/rocsolver_logger.cpp:12:

In file included from /var/tmp/pamac-build-chameleon/rocsolver/src/rocSOLVER-rocm-5.2.3/library/src/include/rocsolver_logger.hpp:7:

/usr/include/fmt/format.h:3122:38: error: implicit instantiation of undefined template 'fmt::detail::dragonbox::float_info<long double>'

    const auto f = basic_fp<typename info::carrier_uint>(converted_value);
                                     ^
/usr/include/fmt/format.h:1408:46: error: implicit instantiation of undefined template 'fmt::detail::dragonbox::float_info<long double>'

    using carrier_uint = typename dragonbox::float_info<Float>::carrier_uint;`

**Comment by cgmb** [comment] 2022-10-01 22:00
I would like to add support for building rocSOLVER using fmt v9, but I should be clear that the official AMD releases use fmt v7 and support for newer versions is provided as best-effort.

Have you reported this problem to the AUR package maintainer, @tpkessler? Manjaro is not a platform that AMD officially supports, and figuring out how to adapt a library to the dependency versions provided by the distro is primarily the job of the distro package maintainer.

**Comment by cgmb** [comment] 2022-10-02 04:51
The AUR bug report for this issue is https://github.com/rocm-arch/rocm-arch/issues/850. A fix was applied in fmt with https://github.com/fmtlib/fmt/commit/0b0f7cfbfcebd021c910078003d413354bd843e2, but there has not yet been a release.

**Comment by cgmb** [comment] 2022-10-02 04:58
As far as I can tell, there's not anything for us to do in rocSOLVER. The problem is due to an unfortunate interaction between clang and fmt, but it should be resolved in the next release of fmt.

**Comment by nidjan** [comment] 2022-10-02 05:28
ok, and now i simple copy fmt7 files  to fmt9 paths, and now build successfully

**Comment by doctorcolinsmith** [comment] 2022-10-26 16:54
Closing as the issue seems to be resolved.

**Closed by doctorcolinsmith** 2022-10-26 16:54 UTC
